import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '../components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
      {/* <!-- from node_modules --> */}
      <script src="node_modules/@material-tailwind/html/scripts/collapse.js"></script>
      {/* <!-- from cdn --> */}
      <script src="https://unpkg.com/@material-tailwind/html@latest/scripts/collapse.js"></script>
    </html>
  )
}
